Repository amakauskaite/baltupiu-softas, pull requests merged in 2018-05, with the labels that each got.

#36 User login and registration backend
  .gitignore
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/UltimateBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserRegistrationBean.java
  project/project-app/src/main/webapp/Registruotis.xhtml
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Administrator.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Cart.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Category.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/User.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/UserAddress.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/UserAddressDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/UserDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/UserAddressDaoImpl.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/UserDaoImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/password/PasswordHashingService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/password/PasswordHashingServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/UserService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/UserServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/address/UserAddressService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/address/UserAddressServiceImpl.java
Labels: Antrinis, Backend

#42 Sidebar implementation and css fixes
  project/project-app/src/main/webapp/cart.xhtml
  project/project-app/src/main/webapp/index.xhtml
  project/project-app/src/main/webapp/login.xhtml
  project/project-app/src/main/webapp/masterSidebar.xhtml
  project/project-app/src/main/webapp/masterTemplate.xhtml
  project/project-app/src/main/webapp/productDetails.xhtml
  project/project-app/src/main/webapp/profile.xhtml
  project/project-app/src/main/webapp/purchaseHistory.xhtml
  project/project-app/src/main/webapp/registration.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
Labels: CSS, Frontend

#45 Header element display
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/webapp/masterHeader.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
Labels: Backend, Frontend

#68 Ui fixes
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/category/CategoryBean.java
  project/project-app/src/main/webapp/index.xhtml
  project/project-app/src/main/webapp/masterSidebar.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
Labels: CSS, Frontend

#71 responsive design error eliminated
  project/project-app/src/main/webapp/index.xhtml
Labels: Frontend, responsive design

#72 Base cart implementation
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/Login.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/ManageCartBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/ProductsBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserRegistrationBean.java
  project/project-app/src/main/webapp/cart.xhtml
  project/project-domain/pom.xml
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Administrator.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Cart.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/CartItem.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Category.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Product.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/UserAddress.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/CartDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/CartDaoImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/CartServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/UserService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/UserServiceImpl.java
Labels: Backend, Frontend, Krepšelis

#73 Admin login page
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/AdminHeaderStatusBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/AdministratorLoginBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/webapp/admin.xhtml
  project/project-app/src/main/webapp/adminHeader.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
Labels: Frontend, UI

#70 admin user list
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/Login.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/admin/UsersBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserRegistrationBean.java
  project/project-app/src/main/webapp/resources/css/master.css
  project/project-app/src/main/webapp/userList.xhtml
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/UserDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/UserDaoImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/ProductService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/ProductServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/UserService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/user/UserServiceImpl.java
Labels: Backend, Frontend

#80 Header and pics
  project/project-app/src/main/webapp/WEB-INF/web.xml
  project/project-app/src/main/webapp/adminHeader.xhtml
  project/project-app/src/main/webapp/masterHeader.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Product.java
Labels: Frontend

#81 Cart functionality improvements
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/ManageCartBean.java
  project/project-app/src/main/webapp/WEB-INF/db/sample.sql
  project/project-app/src/main/webapp/cart.xhtml
  project/project-app/src/main/webapp/index.xhtml
  project/project-app/src/main/webapp/productDetails.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Administrator.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Cart.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/CartItem.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Category.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Product.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/User.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/UserAddress.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/CartService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/CartServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/ProductServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/UserServiceImpl.java
Labels: Backend, Frontend

#78 Admin product back front
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/HeaderStatusBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/admin/UsersBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/AdminProductList.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/CreateProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/DeleteProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/UpdateProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/ProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/category/CategoryBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/webapp/adminHeader.xhtml
  project/project-app/src/main/webapp/adminIndex.xhtml
  project/project-app/src/main/webapp/adminProduct.xhtml
  project/project-app/src/main/webapp/productDetails.xhtml
  project/project-app/src/main/webapp/purchaseHistory.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/CategoryDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/UserDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/CategoryDaoImpl.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/UserDaoImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/CategoryService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/ProductService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/UserService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/CategoryServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/ProductServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/UserServiceImpl.java
Labels: Backend, Frontend, Implementavimas, admin

#90 ui fixes for #87 + product view
  project/project-app/src/main/webapp/adminOrders.xhtml
  project/project-app/src/main/webapp/productDetails.xhtml
  project/project-app/src/main/webapp/purchaseHistory.xhtml
  project/project-app/src/main/webapp/resources/css/master.css
Labels: Frontend, enhancement

#69 Interseptors
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/AdministratorLogin.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/UltimateBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/admin/UsersBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/AdministratorLoginBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/CreateProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/DeleteProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/administrator/UpdateProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/cart/ManageCartBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/cart_history/AdministratorCartBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/cart_history/UserCartHistoryBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/ProductBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/ProductsBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/products/category/CategoryBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserLoginBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserRegistrationBean.java
  project/project-app/src/main/java/lt/baltupiusoftas/project/app/user/UserUpdateBean.java
  project/project-domain/src/main/java/lt/baltupiusoftas/project/domain/Logger.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/LoggerDao.java
  project/project-persistence/src/main/java/lt/baltupiusoftas/project/persistence/impl/LoggerDaoImpl.java
  project/project-persistence/src/main/resources/META-INF/beans.xml
  project/project-persistence/src/main/resources/META-INF/persistence.xml
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/LoggerService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/impl/LoggerServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/intersector/ActionsLoggerService.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/intersector/ActionsLoggerServiceImpl.java
  project/project-service/src/main/java/lt/baltupiusoftas/project/service/intersector/LoggedInvocation.java
  project/project-service/src/main/resources/META-INF/beans.xml
  project/project-service/src/test/java/lt/baltupiusoftas/project/service/messaging/MessagingServiceTest.java
Labels: Backend, Database, enhancement
